openapi: 3.1.0
info:
  title: Sales
  version: '1.0'
  summary: DropEngine™ Sales API
servers:
  - url: 'https://dev.drop-engine.com/api/v1/sales'
    description: Dev
paths:
  /orders:
    get:
      summary: Get Orders
      tags:
        - v1.0
        - orders
      responses: {}
      operationId: get-orders
    post:
      summary: Create Order
      tags:
        - v1.0
        - orders
      responses: {}
      operationId: post-orders
    delete:
      summary: Delete Order
      tags:
        - v1.0
        - orders
      responses: {}
      operationId: delete-orders
  '/orders/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Order ID
    get:
      summary: Get Order
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/SalesOrderDto'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                  message:
                    type: string
                    minLength: 1
                  error:
                    type: string
                    minLength: 1
                required:
                  - id
                  - message
                  - error
                x-examples:
                  example-1:
                    id: 6259fce47ddc5db601cc1bbf
                    message: 'SalesOrder not found with ID: 6259fce47ddc5db601cc1bbf'
                    error: SALES_ORDER_NOT_FOUND
              examples:
                'Error: Not Found':
                  value:
                    id: 6259fce47ddc5db601cc1bbf
                    message: 'SalesOrder not found with ID: 6259fce47ddc5db601cc1bbf'
                    error: SALES_ORDER_NOT_FOUND
      operationId: get-orders-id
      description: Lookup SalesOrder by ID.
  '/orders/{id}/lineItems/{lid}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
      - schema:
          type: string
        name: lid
        in: path
        required: true
    patch:
      summary: Edit Personalization
      operationId: patch-orders-id-lineItems-lid
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Sales/CreateSalesOrder/CreateSalesOrderLineItem.json
  '/orders/{id}/shippingAddress':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    patch:
      summary: Edit ShippingAddress
      operationId: patch-orders-id-shippingAddress
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Shared/Address.json
  '/orders/{id}/customer':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    patch:
      summary: Edit Customer
      operationId: patch-orders-id-customer
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Sales/CreateSalesOrder/CreateSalesOrderCustomer.json
  '/orders/{id}/send':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: Send To Manufacturer
      operationId: post-orders-id-send
      responses:
        '200':
          description: OK
  '/orders/{id}/recall':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: Recall From Manufacturer
      operationId: post-orders-id-recall
      responses:
        '200':
          description: OK
      description: ''
  '/orders/{id}/cancel':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: Cancel Order
      operationId: post-orders-id-cancel
      responses:
        '200':
          description: OK
      description: ''
components:
  schemas:
    DomainEvent:
      title: DomainEvent
      type: object
      properties:
        id:
          type: string
  responses:
    QueryProductsResponseDto:
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                data:
                  - uuid: e06cc34d-6979-44b2-9fdc-54fbb7edc05f
                    sku: MU-C001-00
                    type: 2DMetalArt
                    pricingTier: '1'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C001-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/2133323496/7329271441/MU-C001-00.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: fff90a63-6b5b-4b01-a7be-6a5205ecf7c5
                    sku: MU-C004-00
                    type: 2DMetalArt
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C004-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/5747787946/1486874782/MU-C004-00.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: 1aab0038-5211-4017-8263-a6f437c83b7e
                    sku: MU-C005-00
                    type: 2DMetalArt
                    pricingTier: '3'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C005-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/7191694457/7636424154/MU-C005-00.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                    variants: []
                    productType: null
                  - uuid: 0c1f7dac-3547-47c2-ac13-034c3a653175
                    sku: MU-C116-00
                    type: 2DMetalArt
                    pricingTier: '3'
                    tags:
                      - Steel
                      - Custom
                      - Outdoors
                      - Tree
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C116-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/7737486998/1891427748/MU-C116-00.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: middle_text
                        type: input
                        label: Middle Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                    variants: []
                    productType: null
                  - uuid: 50118145-07b4-41d0-8841-b20dbbc6d8ed
                    sku: MU-C017-00
                    type: 2DMetalArt
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C017-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/8846864191/5233468681/MU-C017-00.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: 1b9f757b-45bc-4b42-a615-b42e47b197de
                    sku: MEM-27-00
                    type: 2DMetalArt
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Nurse
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MEM-27-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/3499663496/9643599499/27_04.20.2021.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                    variants: []
                    productType: null
                  - uuid: a54b0ff1-3611-473b-9dd5-68d7ed950a6f
                    sku: MU2-C001-00
                    type: Canvas
                    pricingTier: '1'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C001-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/2133323496/7329271441/MU-C001-00.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: a2214160-bac2-4987-a073-24f849c31f36
                    sku: MU2-C004-00
                    type: Canvas
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C004-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/5747787946/1486874782/MU-C004-00.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: af931398-6aaa-4366-bbde-2c124edb7ea1
                    sku: MU2-C005-00
                    type: Canvas
                    pricingTier: '3'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C005-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/7191694457/7636424154/MU-C005-00.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                    variants: []
                    productType: null
                  - uuid: cb7c22fc-d16d-42d5-a692-fc7d07919ab5
                    sku: MU2-C116-00
                    type: Canvas
                    pricingTier: '3'
                    tags:
                      - Steel
                      - Custom
                      - Outdoors
                      - Tree
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C116-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/7737486998/1891427748/MU-C116-00.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: middle_text
                        type: input
                        label: Middle Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                    variants: []
                    productType: null
                  - uuid: 6d39c9d5-3b9a-4e22-bb01-6e4ce1bd8200
                    sku: MU2-C017-00
                    type: Canvas
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C017-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/8846864191/5233468681/MU-C017-00.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: 94bd8389-d620-4ccc-9710-118370ea10c7
                    sku: MU2-27-00
                    type: Canvas
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Nurse
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MEM-27-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/3499663496/9643599499/27_04.20.2021.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                    variants: []
                    productType: null
                page: 0
                pages: 1
                query: ''
                size: 12
                total: 12
            properties:
              data:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  $ref: '#/components/schemas/Product'
              page:
                type: number
              pages:
                type: number
              query:
                type: string
              size:
                type: number
              total:
                type: number
            required:
              - data
              - page
              - pages
              - query
              - size
              - total
          examples:
            GetProducts (Default):
              value:
                data:
                  - uuid: e06cc34d-6979-44b2-9fdc-54fbb7edc05f
                    sku: MU-C001-00
                    type: 2DMetalArt
                    pricingTier: '1'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C001-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/2133323496/7329271441/MU-C001-00.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: fff90a63-6b5b-4b01-a7be-6a5205ecf7c5
                    sku: MU-C004-00
                    type: 2DMetalArt
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C004-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/5747787946/1486874782/MU-C004-00.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: 1aab0038-5211-4017-8263-a6f437c83b7e
                    sku: MU-C005-00
                    type: 2DMetalArt
                    pricingTier: '3'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C005-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/7191694457/7636424154/MU-C005-00.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                    variants: []
                    productType: null
                  - uuid: 0c1f7dac-3547-47c2-ac13-034c3a653175
                    sku: MU-C116-00
                    type: 2DMetalArt
                    pricingTier: '3'
                    tags:
                      - Steel
                      - Custom
                      - Outdoors
                      - Tree
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C116-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/7737486998/1891427748/MU-C116-00.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: middle_text
                        type: input
                        label: Middle Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                    variants: []
                    productType: null
                  - uuid: 50118145-07b4-41d0-8841-b20dbbc6d8ed
                    sku: MU-C017-00
                    type: 2DMetalArt
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C017-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/8846864191/5233468681/MU-C017-00.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: 1b9f757b-45bc-4b42-a615-b42e47b197de
                    sku: MEM-27-00
                    type: 2DMetalArt
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Nurse
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MEM-27-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/3499663496/9643599499/27_04.20.2021.svg'
                    createdAt: '2022-03-24T20:43:26.000Z'
                    updatedAt: '2022-03-24T20:43:26.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                    variants: []
                    productType: null
                  - uuid: a54b0ff1-3611-473b-9dd5-68d7ed950a6f
                    sku: MU2-C001-00
                    type: Canvas
                    pricingTier: '1'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C001-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/2133323496/7329271441/MU-C001-00.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: a2214160-bac2-4987-a073-24f849c31f36
                    sku: MU2-C004-00
                    type: Canvas
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C004-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/5747787946/1486874782/MU-C004-00.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: af931398-6aaa-4366-bbde-2c124edb7ea1
                    sku: MU2-C005-00
                    type: Canvas
                    pricingTier: '3'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C005-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/7191694457/7636424154/MU-C005-00.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                    variants: []
                    productType: null
                  - uuid: cb7c22fc-d16d-42d5-a692-fc7d07919ab5
                    sku: MU2-C116-00
                    type: Canvas
                    pricingTier: '3'
                    tags:
                      - Steel
                      - Custom
                      - Outdoors
                      - Tree
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C116-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/7737486998/1891427748/MU-C116-00.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: top_text
                        type: input
                        label: Top Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                      - name: middle_text
                        type: input
                        label: Middle Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: bottom_text
                        type: input
                        label: Bottom Text
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 24
                        placeholder: Enter up to 24 characters
                    variants: []
                    productType: null
                  - uuid: 6d39c9d5-3b9a-4e22-bb01-6e4ce1bd8200
                    sku: MU2-C017-00
                    type: Canvas
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Initial
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C017-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/8846864191/5233468681/MU-C017-00.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                      - name: initial
                        type: dropdown
                        label: Initial
                        options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        required: true
                        placeholder: Select Initial
                    variants: []
                    productType: null
                  - uuid: 94bd8389-d620-4ccc-9710-118370ea10c7
                    sku: MU2-27-00
                    type: Canvas
                    pricingTier: '2'
                    tags:
                      - Steel
                      - Custom
                      - Nurse
                    image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MEM-27-00-Black.png'
                    svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/3499663496/9643599499/27_04.20.2021.svg'
                    createdAt: '2022-03-24T19:19:00.000Z'
                    updatedAt: '2022-03-24T19:19:00.000Z'
                    customOptions:
                      - name: name
                        type: input
                        label: Name
                        pattern: 'A-Z,a-z,0-9'
                        required: true
                        maxLength: 16
                        placeholder: Enter up to 16 characters
                    variants: []
                    productType: null
                page: 0
                pages: 1
                query: ''
                size: 12
                total: 12
            Empty:
              value:
                data: []
                page: 0
                pages: 1
                query: ''
                size: 0
                total: 0
    QueryOrdersResponseDto:
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                total: 0
                page: 0
                pages: 0
                size: 100
                options: []
                data: []
            properties:
              total:
                type: number
              page:
                type: number
              pages:
                type: number
              size:
                type: number
              options:
                type: array
                items:
                  type: object
              data:
                type: array
                items:
                  $ref: ../models/Sales/Shared/SalesOrder.json
            required:
              - total
              - page
              - pages
              - size
              - options
              - data
          examples:
            Example Response:
              value:
                total: 0
                page: 0
                pages: 0
                size: 100
                options: []
                data:
                  - id: 6270277eb0e7a7ca40b015cd
                    orderName: SLI-3838315397200
                    orderStatus: OPEN
                    orderDate: '2022-05-02T18:48:30.131Z'
                    orderNumber: 1001
                    customer:
                      email: test@example.com
                      name: Test Example
                    shippingAddress:
                      zip: 43844-9406
                      city: Warsaw
                      name: Tony Stark
                      phone: '2563472777'
                      company: MyEasySuite Inc.
                      country: United States
                      address1: 19936 County Road 18
                      address2: ''
                      address3: ''
                      latitude: 40.2496938
                      longitude: -82.1265222
                      province: Ohio
                      lastName: Stark
                      firstName: Tony
                      countryCode: US
                      provinceCode: OH
                    billingAddress:
                      zip: 43844-9406
                      city: Warsaw
                      name: Tony Stark
                      phone: '2563472777'
                      company: MyEasySuite Inc.
                      country: United States
                      address1: 19936 County Road 18
                      address2: ''
                      address3: ''
                      latitude: 40.2496938
                      longitude: -82.1265222
                      province: Ohio
                      lastName: Stark
                      firstName: Tony
                      countryCode: US
                      provinceCode: OH
                    lineItems:
                      - id: 6270277eb0e7a7ca40b015ce
                        lineNumber: 1
                        quantity: 1
                        variant:
                          id: 6e4971dc-6c71-4ae9-a451-3f557b8d97e8
                          sku: MU-C004-00-24-Black
                          image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C004-00-Black.png'
                          svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/5747787946/4384264343/MU-C004-00.svg'
                          type: 2DMetalArt
                          option1:
                            name: Size
                            option: 24"
                            enabled: true
                          option2:
                            name: Color
                            option: Black
                            enabled: true
                          option3:
                            option: null
                            enabled: false
                          manufacturingCost:
                            currency: USD
                            total: 800
                          shippingCost:
                            currency: USD
                            total: 1300
                          weight:
                            units: oz
                            dimension: 1194
                          productionData:
                            material: Mild Steel
                            thickness: '0.06'
                            route: '1'
                          personalizationRules:
                            - name: top_text
                              label: Top Text
                              placeholder: Enter up to 14 characters
                              required: true
                              type: input
                              maxLength: 14
                              pattern: '^[a-zA-Z0-9\s!?.,\’”()&$%#@/]*$'
                              options: ''
                            - name: bottom_text
                              label: Bottom Text
                              placeholder: Enter up to 14 characters
                              required: true
                              type: input
                              maxLength: 14
                              pattern: '^[a-zA-Z0-9\s!?.,\’”()&$%#@/]*$'
                              options: ''
                            - name: initial
                              label: Initial
                              placeholder: Select your initial here
                              required: true
                              type: dropdownlist
                              maxLength: 0
                              options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        personalization:
                          - name: Top Text
                            value: TestExampleLongerThan14
                          - name: Bottom Text
                            value: Test-Example
                        flags:
                          - type: InvalidPersonalization
                            details:
                              lineNumber: 1
                              property: Top Text
                              reason: INVALID_LENGTH
                            message: 'Line Item #1 has invalid property ''Top Text'': ''undefined''. Reason: INVALID_LENGTH'
                          - type: BadCharacter
                            details:
                              lineNumber: 1
                              property: Bottom Text
                              value: Test-Example
                              pattern: '^[a-zA-Z0-9\s!?.,\’”()&$%#@/]*$'
                              reason: BAD_CHARACTER
                            message: 'Line Item #1 has a bad character in property ''Bottom Text'': ''Test-Example''. Reason: BAD_CHARACTER'
                          - type: MissingPersonalization
                            details:
                              lineNumber: 1
                              property: Initial
                              reason: MISSING
                            message: 'Line Item #1 is missing property ''Initial''.'
                        createdAt: '2022-05-02T18:55:41.584Z'
                        updatedAt: '2022-05-02T18:55:41.584Z'
                      - id: 6270277eb0e7a7ca40b015cf
                        lineNumber: 2
                        quantity: 1
                        variant:
                          id: ed45942e-5f80-447e-bca3-a4bcc8d27088
                          sku: MU-C004-00-18-Black
                          image: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/Product/01+-+Product+Variant+Images/01+-+White+Backdrop/MU-C004-00-Black.png'
                          svg: 'https://prodmyeasymonogram.s3.us-east-2.amazonaws.com/preview_images/5747787946/4384264343/MU-C004-00.svg'
                          type: 2DMetalArt
                          option1:
                            name: Size
                            option: 18"
                            enabled: true
                          option2:
                            name: Color
                            option: Black
                            enabled: true
                          option3:
                            option: null
                            enabled: false
                          manufacturingCost:
                            currency: USD
                            total: 650
                          shippingCost:
                            currency: USD
                            total: 1200
                          weight:
                            units: oz
                            dimension: 738
                          productionData:
                            material: Mild Steel
                            thickness: '0.06'
                            route: '1'
                          personalizationRules:
                            - name: top_text
                              label: Top Text
                              placeholder: Enter up to 14 characters
                              required: true
                              type: input
                              maxLength: 14
                              pattern: '^[a-zA-Z0-9\s!?.,\’”()&$%#@/]*$'
                              options: ''
                            - name: bottom_text
                              label: Bottom Text
                              placeholder: Enter up to 14 characters
                              required: true
                              type: input
                              maxLength: 14
                              pattern: '^[a-zA-Z0-9\s!?.,\’”()&$%#@/]*$'
                              options: ''
                            - name: initial
                              label: Initial
                              placeholder: Select your initial here
                              required: true
                              type: dropdownlist
                              maxLength: 0
                              options: 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z'
                        personalization:
                          - name: Name
                            value: TestExample
                        flags:
                          - type: MissingPersonalization
                            details:
                              lineNumber: 2
                              property: Top Text
                              reason: MISSING
                            message: 'Line Item #2 is missing property ''Top Text''.'
                          - type: MissingPersonalization
                            details:
                              lineNumber: 2
                              property: Bottom Text
                              reason: MISSING
                            message: 'Line Item #2 is missing property ''Bottom Text''.'
                          - type: MissingPersonalization
                            details:
                              lineNumber: 2
                              property: Initial
                              reason: MISSING
                            message: 'Line Item #2 is missing property ''Initial''.'
                        createdAt: '2022-05-02T18:55:41.584Z'
                        updatedAt: '2022-05-02T18:55:41.584Z'
    SalesOrderDto:
      description: Example response
      content:
        application/json:
          schema:
            $ref: ../models/Sales/Shared/SalesOrder.json
tags:
  - name: sales
  - name: v1
